# Generated by Django 4.1.2 on 2022-10-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_vehicle_is_charging'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='start_session',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='stop_session',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
