# Generated by Django 4.1.2 on 2022-10-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_vehicle_start_session_vehicle_stop_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='total_last_session',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
