# Generated by Django 4.1.2 on 2022-10-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_vehicle_total_last_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='total_last_session',
            new_name='total_time_last_session',
        ),
    ]
