# Generated by Django 4.1.2 on 2022-10-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_rename_total_last_session_vehicle_total_time_last_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='count_kw',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
