# Generated by Django 4.1.2 on 2022-10-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_rename_charges_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='snapshot_time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
