# Generated by Django 4.1.2 on 2022-10-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_charge_snapshot_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='user',
        ),
    ]
