# Generated by Django 4.1.2 on 2022-10-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_remove_charge_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='count_kw',
            new_name='average_count_kw_last_session',
        ),
    ]
