# Generated by Django 4.1.2 on 2022-11-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_vehicle_average_count_kwh_last_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plot',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
